const countries = [
    { label: "Afghanistan", value: "AF" },
    { label: "Armenia", value: "AM" },
    { label: "Azerbaijan", value: "AZ" },
    { label: "Bahrain", value: "BH" },
    { label: "Bangladesh", value: "BD" },
    { label: "Bhutan", value: "BT" },
    { label: "Brunei", value: "BN" },
    { label: "Cambodia", value: "KH" },
    { label: "China", value: "CN" },
    { label: "Cyprus", value: "CY" },
    { label: "Georgia", value: "GE" },
    { label: "India", value: "IN" },
    { label: "Indonesia", value: "ID" },
    { label: "Iran", value: "IR" },
    { label: "Iraq", value: "IQ" },
    { label: "Israel", value: "IL" },
    { label: "Japan", value: "JP" },
    { label: "Jordan", value: "JO" },
    { label: "Kazakhstan", value: "KZ" },
    { label: "Kuwait", value: "KW" },
    { label: "Kyrgyzstan", value: "KG" },
    { label: "Laos", value: "LA" },
    { label: "Lebanon", value: "LB" },
    { label: "Malaysia", value: "MY" },
    { label: "Maldives", value: "MV" },
    { label: "Mongolia", value: "MN" },
    { label: "Myanmar (Burma)", value: "MM" },
    { label: "Nepal", value: "NP" },
    { label: "North Korea", value: "KP" },
    { label: "Oman", value: "OM" },
    { label: "Pakistan", value: "PK" },
    { label: "Palestine", value: "PS" },
    { label: "Philippines", value: "PH" },
    { label: "Qatar", value: "QA" },
    { label: "Saudi Arabia", value: "SA" },
    { label: "Singapore", value: "SG" },
    { label: "South Korea", value: "KR" },
    { label: "Sri Lanka", value: "LK" },
    { label: "Syria", value: "SY" },
    { label: "Taiwan", value: "TW" },
    { label: "Tajikistan", value: "TJ" },
    { label: "Thailand", value: "TH" },
    { label: "Timor-Leste", value: "TL" },
    { label: "Turkey", value: "TR" },
    { label: "Turkmenistan", value: "TM" },
    { label: "United Arab Emirates", value: "AE" },
    { label: "Uzbekistan", value: "UZ" },
    { label: "Vietnam", value: "VN" },
    { label: "Yemen", value: "YE" }
  ];
  
  export default countries;
  